### ISSUE TITLE
0.9.2. Failed to start a new tunnel with bypass option.

### ISSUE THREAD

**Issue by shackijj** [crossbrowsertesting/cbt-tunnel-nodejs#13]
When I trying to start a new tunnel with bypass options (either boolean or string) I get the error
```
cmdArgs.bypass.toLowerCase is not a function
```

That happens because the option is coerced to boolean at /cbt_tunnels/tunnel_start.js: 178

How about covering parameters validation with unit tests? AFAIR, it's not the first time when params validation got broken after release.

I could help with implementation. Just let me know.

**Comment by sydneybrokeit** [comment]
@rosesandhello I am able to recreate this issue.

**Comment by sydneybrokeit** [comment]
Correction - looks like you've already fixed it in the latest commit.

**Comment by shackijj** [comment]
When a new version will be released?

**Comment by sydneybrokeit** [comment]
Should have a new version out later today for npm.  If you need it faster, you can clone the repo for the time being, and then upgrade in npm when it's available.

**Comment by rosesandhello** [comment]
Addressed in the [latest release](https://github.com/crossbrowsertesting/cbt-tunnel-nodejs/releases/tag/v0.9.3). Thanks for pointing this out!
