### ISSUE TITLE
latest release without file extension

### ISSUE THREAD

**Issue by mikeliucc** [crossbrowsertesting/cbt-tunnel-nodejs#23]
Hi,

I see the release page doesn't have file extension for Mac and Linux:
![image](https://user-images.githubusercontent.com/8107782/62474923-d03a5680-b758-11e9-95ea-8dda21e90d17.png)

It is not clear what type of files they are (for Mac or Linux).

In comparison, the previous release page looks like this:
![image](https://user-images.githubusercontent.com/8107782/62474896-c44e9480-b758-11e9-824e-c7a7b8954394.png)

I think it's much clearer having the file extension (.zip for Mac and Linux). 

Is the removal of extension intentional, and if so, please kindly provide some clarification and instruction as to how these files should be handled.

Thanks.

**Comment by chasecook412** [comment]
@mikeliucc We appreciate you catching that and letting us know! The files found in the latest release should be corrected now.
