### ISSUE TITLE
unable to install using NPM due to access issue with pac-resolver dependency

### ISSUE THREAD

**Issue by kshrestha99** [crossbrowsertesting/cbt-tunnel-nodejs#24]
I am trying to install cbt_tunnels but I get this error: fatal: "unable to access 'https://github.com/rosesandhello/node-pac-resolver.git/' . I was wondering if there was any reason to use that repo which seems like it is not published in NPM registry (hence the use of github repo)  instead of something already in NPM like https://github.com/TooTallNate/node-pac-resolver?
I cannot get my machine to install cbt_tunnels because of this issue. Please advice!

**Comment by tonetheman** [comment]
Do you have git installed and in the PATH?

**Comment by kshrestha99** [comment]
I do, i think our corporate proxy is blocking access to that repo. And I can’t find a NPM installer for that repo. I am guessing it would have been better if that package was published in the NPM registry.

**Comment by kshrestha99** [comment]
jreese802 Thank you for your prompt update! Our whole team is pleasantly surprised how quickly you responded to our request. Thank you again!

**Comment by jreese802** [comment]
You're welcome! This was something we meant to do but kept putting off. Glad it's working for you guys now!
