### ISSUE TITLE
Add quiet mode.

### ISSUE THREAD

**Issue by shackijj** [crossbrowsertesting/cbt-tunnel-nodejs#8]
Hello!
Showing traffic handling could be useless while using cbt_tunnels through nodejs. Furthermore, graphics which are drawn in stdout, broke output of application which uses cbt_tunnels.

**Comment by rosesandhello** [comment]
A variation on your pull request will be considered for a future version.

**Comment by shackijj** [comment]
Why the issue was closed? Is it solved?

**Comment by rosesandhello** [comment]
Added in latest commit. Will be incorporated in next release.

**Comment by shackijj** [comment]
The problem was not solved. 

This how i tested it.
`const cbt = require('./cbt-tunnel-nodejs/tunnel_start');

cbt.start({
        username: 'BOO',
        authkey: 'FOO',
    },
    (err) => {
        if (err) {
            console.log('CBT tunnel is failed', err);
            process.exit(1);
        }
        console.log('CBT tunnel is up');
        console.log('Wait for tunnel registratiuon');

        setTimeout(() => {
            console.log('CBT setup is done');
            cbt.stop();
        }, 5000);
    });
`

The output should be:

Getting account info...
Got user account info!
POST request to CBT for a tunnel...
Posted!
Started connection attempt!
Connecting as simpleproxy...
PUT request to CBT finalizing tunnel...
PUT request successful!
Completely connected!
CBT tunnel is up
Wait for tunnel registratiuon
CBT setup is done
Bye!


Currently, when I call .stop method application writes to stdout (see screenshot below)
![cbt-screenshot](https://cloud.githubusercontent.com/assets/9201657/25239275/3c1febfc-25f8-11e7-985e-a14ca71aa9cb.jpg)

Please keep the issue open while it's not solved and released.

Btw, you can give feedback on https://github.com/crossbrowsertesting/cbt-tunnel-nodejs/pull/9.

**Comment by rosesandhello** [comment]
Give the latest commit a go.

**Comment by shackijj** [comment]
It works. Thank!
